spring.application.name=parking-api
# URL de conexão: troque 'nome_do_seu_banco' pelo nome real do banco que você criou
spring.datasource.url=jdbc:postgresql://localhost:5432/parking
spring.datasource.username=postgres
spring.datasource.password=password

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always

# Configurações do Hibernate/JPA
# 'update' cria as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
# Mostra no console os comandos SQL que o Spring está executando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect